import {genNamspace} from '@src/utils/reduxUtils';

const n = genNamspace('ACCOUNT');

// define types here
const TYPES = {
  SET: n('SET'),
  SET_LIST: n('SET_LIST'),
  REMOVE_BY_NAME: n('REMOVE_BY_NAME'),
  GET_BALANCE: n('GET_BALANCE'),
  GET_BALANCE_FINISH: n('GET_BALANCE_FINISH'),
  SET_DEFAULT_ACCOUNT: n('SET_DEFAULT_ACCOUNT'),
  ACTION_IMPORT_ACCOUNT_FETCHING: n('ACTION_IMPORT_ACCOUNT_FETCHING'),
  ACTION_IMPORT_ACCOUNT_FETCHED: n('ACTION_IMPORT_ACCOUNT_FETCHED'),
  ACTION_IMPORT_ACCOUNT_ERROR: n('ACTION_IMPORT_ACCOUNT_ERROR'),
  ACTION_CREATE_ACCOUNT_FETCHING: n('ACTION_CREATE_ACCOUNT_FETCHING'),
  ACTION_CREATE_ACCOUNT_FETCHED: n('ACTION_CREATE_ACCOUNT_FETCHED'),
  ACTION_CREATE_ACCOUNT_ERROR: n('ACTION_CREATE_ACCOUNT_ERROR'),
};

export default TYPES;
